apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: 10.45.59.250/k8s/nginx:latest
        ports:
        - containerPort: 80
